spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://localhost:3306/nail_salon?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
  servlet:
    application-display-name: NailSalon

file:
  upload-dir: src/main/resources/static/uploads


new:
  app:
    api:
      url: http://localhost:8082/api/designs

app:
    admin:
      username: ${APP_ADMIN_USERNAME=gabz}  // Add you environment Variables!
      password: ${APP_ADMIN_PASSWORD=gabz}

